# Site settings
# These are used to personalize your new site.
title: Nicholas A. Mikulski # your name here
logo: "/images/self.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Arts in Applied Computing: Business Concentration (class of 2027)
  <br /><br />
  <a href="https://drive.google.com/file/d/1-Lyo5kI5BoTUq02NKJBXP9iZCmW0uo5i/view?usp=sharing">View My Resume</a>
  <br /><br />
  <a href="https://app.joinhandshake.com/profiles/b2pb4a">View My Handshake Profile</a>
repository: "Nickam147/Nickam147.github.io"
github_username:  Nickam147 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

